'use strict';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const money = n => new Intl.NumberFormat('vi-VN', {style:'currency',currency:'VND'}).format(n);
const escapeHTML = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize = s => s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
const categories={all:'Tất cả',snacks:'Bánh & kẹo',chocolate:'Chocolate',skincare:'Chăm sóc da',supplements:'Thực phẩm bổ sung'};
const state={category:'all',brand:'all',sort:'featured',query:'',cart:new Map(),orders:[],session:null};
const shippingFee=30000;
const storageKeys={accounts:'banhkeongoai_accounts_v1',products:'banhkeongoai_products_v1',session:'banhkeongoai_session_v1'};
function readJSON(store,key,fallback){try{const value=JSON.parse(store.getItem(key));return value??fallback}catch{return fallback}}
function writeJSON(store,key,value){try{store.setItem(key,JSON.stringify(value));return true}catch{toast('Trình duyệt không thể lưu thay đổi trên thiết bị này.');return false}}
function validStoredProduct(p){return p&&typeof p.id==='string'&&typeof p.name==='string'&&typeof p.brand==='string'&&Object.hasOwn(categories,p.category)&&p.category!=='all'&&Number.isSafeInteger(p.price)&&p.price>=1000&&Number.isSafeInteger(p.stock)&&p.stock>=0&&typeof p.image==='string'}
function loadLocalProducts(){const saved=readJSON(localStorage,storageKeys.products,null);if(Array.isArray(saved)&&saved.length&&saved.every(validStoredProduct))PRODUCTS.splice(0,PRODUCTS.length,...saved)}
function persistProducts(){writeJSON(localStorage,storageKeys.products,PRODUCTS)}
function accounts(){const list=readJSON(localStorage,storageKeys.accounts,[]);return Array.isArray(list)?list:[]}
function bytesToBase64(bytes){let raw='';bytes.forEach(byte=>raw+=String.fromCharCode(byte));return btoa(raw)}
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256);return bytesToBase64(new Uint8Array(bits))}
async function makeAccount(name,email,password,role){const list=accounts(),normalizedEmail=email.trim().toLowerCase();if(list.some(a=>a.email===normalizedEmail))throw new Error('Email này đã được đăng ký trên thiết bị.');const salt=crypto.getRandomValues(new Uint8Array(16));const account={id:crypto.randomUUID(),name:name.trim(),email:normalizedEmail,role,salt:bytesToBase64(salt),passwordHash:await passwordHash(password,salt)};if(!writeJSON(localStorage,storageKeys.accounts,[...list,account]))throw new Error('Không thể lưu tài khoản.');return account}
async function authenticate(email,password,role){const account=accounts().find(a=>a.email===email.trim().toLowerCase()&&a.role===role);if(!account)return null;const salt=Uint8Array.from(atob(account.salt),c=>c.charCodeAt(0));return await passwordHash(password,salt)===account.passwordHash?account:null}
function setSession(account){state.session={id:account.id,name:account.name,email:account.email,role:account.role};writeJSON(sessionStorage,storageKeys.session,state.session);renderAccount()}
function renderAccount(){const s=state.session;$('#account-guest').hidden=!!s;$('#account-session').hidden=!s;$('#account-label').textContent=s?s.name.split(/\s+/).slice(-1)[0]:'Đăng nhập';if(!s)return;$('#account-avatar').textContent=(s.name||s.email).charAt(0).toUpperCase();$('#session-name').textContent=s.name;$('#session-email').textContent=s.email;$('#session-role').textContent=s.role==='admin'?'Chủ cửa hàng':'Khách hàng';$('#open-dashboard').hidden=s.role!=='admin'}
const findProduct=id=>PRODUCTS.find(p=>p.id===id);
const cartItems=()=>[...state.cart].map(([id,qty])=>({...findProduct(id),qty}));
const subtotal=()=>cartItems().reduce((sum,p)=>sum+p.price*p.qty,0);
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function openDialog(id){const d=$(id);if(!d.open)d.showModal()}
function closeDialog(id){$(id).close()}
function visibleProducts(){let list=PRODUCTS.filter(p=>(state.category==='all'||p.category===state.category)&&(state.brand==='all'||p.brand===state.brand)&&normalize(p.name+' '+p.brand+' '+categories[p.category]).includes(normalize(state.query)));if(state.sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(state.sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'vi'));return list}
function renderCatalog(){const list=visibleProducts();$('#product-grid').innerHTML=list.map(p=>`<article class="product-card"><button class="product-image" data-detail="${escapeHTML(p.id)}" aria-label="Xem ${escapeHTML(p.name)}"><span class="category-label">${p.sellerProvided?'Ảnh tham khảo':categories[p.category]}</span><img src="${escapeHTML(p.image)}" alt="${escapeHTML(p.name)}" width="240" height="240" loading="lazy"></button><div class="product-info"><span class="product-brand">${escapeHTML(p.brand)}</span><button class="product-name" data-detail="${escapeHTML(p.id)}">${escapeHTML(p.name)}</button><span class="product-size">${escapeHTML(p.size)} · ${p.stock>0?'Có sẵn (mẫu)':'Hết hàng (mẫu)'}</span><div class="product-bottom"><span class="price">${money(p.price)}</span><button class="add-button" data-add="${escapeHTML(p.id)}" aria-label="Thêm ${escapeHTML(p.name)} vào giỏ" ${p.stock===0?'disabled':''}>+</button></div></div></article>`).join('');$('#no-results').hidden=list.length>0;$('#result-count').textContent=list.length+' sản phẩm';const count=$('#category-chips [data-category="all"] span');if(count)count.textContent=PRODUCTS.length;$$('[data-category]').forEach(b=>{b.classList.toggle('active',b.dataset.category===state.category);b.setAttribute('aria-pressed',String(b.dataset.category===state.category))});$('#reset-filters').hidden=state.category==='all'&&state.brand==='all'&&!state.query&&state.sort==='featured'}
function chooseCategory(category,scroll=true){if(!Object.hasOwn(categories,category))throw new Error('Danh mục không hợp lệ');state.category=category;renderCatalog();if(scroll)$('#catalog').scrollIntoView({behavior:'smooth',block:'start'})}
function clearFilters(){state.category='all';state.brand='all';state.query='';state.sort='featured';$('#search').value='';$('#brand').value='all';$('#sort').value='featured';renderCatalog()}
function addToCart(id,qty=1){const p=findProduct(id);if(!p||!Number.isInteger(qty)||qty<1)throw new Error('Sản phẩm hoặc số lượng không hợp lệ');const next=(state.cart.get(id)||0)+qty;if(next>p.stock){toast('Số lượng vượt tồn kho minh họa ('+p.stock+').');return false}state.cart.set(id,next);renderCart();toast('Đã thêm '+p.name+' vào giỏ');return true}
function changeQty(id,delta){const current=state.cart.get(id);if(!current)return;const next=current+delta;if(next<=0)state.cart.delete(id);else if(next<=findProduct(id).stock)state.cart.set(id,next);else toast('Đã đạt số lượng tồn kho minh họa.');renderCart()}
function summaryHTML(){return `<div class="sum-row"><span>Tạm tính</span><span>${money(subtotal())}</span></div><div class="sum-row"><span>Giao hàng (minh họa)</span><span>${money(shippingFee)}</span></div><div class="sum-row total"><span>Tổng cộng</span><span>${money(subtotal()+shippingFee)}</span></div>`}
function renderCart(){const items=cartItems();$('#cart-count').textContent=items.reduce((s,p)=>s+p.qty,0);if(!items.length){$('#cart-content').innerHTML='<div class="empty-state"><h3>Giỏ hàng đang trống</h3><p>Thêm một món yêu thích để bắt đầu.</p><button class="button primary" id="continue-shopping">Khám phá cửa hàng ↗</button></div>';return}$('#cart-content').innerHTML=items.map(p=>`<div class="cart-row"><img src="${p.image}" alt="${escapeHTML(p.name)}"><div><h3>${escapeHTML(p.name)}</h3><span class="muted small">${escapeHTML(p.size)} · ${money(p.price)}</span><div class="row-bottom"><div class="quantity"><button data-qty="${p.id}" data-delta="-1" aria-label="Giảm số lượng ${escapeHTML(p.name)}">−</button><span aria-label="Số lượng">${p.qty}</span><button data-qty="${p.id}" data-delta="1" aria-label="Tăng số lượng ${escapeHTML(p.name)}" ${p.qty>=p.stock?'disabled':''}>+</button></div><strong class="small">${money(p.price*p.qty)}</strong><button class="remove" data-remove="${p.id}" aria-label="Xóa ${escapeHTML(p.name)}">Xóa</button></div></div></div>`).join('')+`<div class="cart-total">${summaryHTML()}<p class="notice">Giá theo thông tin cửa hàng hoặc dữ liệu mẫu. Phí giao hàng và đơn đặt hàng chỉ để thử nghiệm.</p><button class="button primary full" id="start-checkout">Tiếp tục đặt hàng <span aria-hidden="true">→</span></button><button class="text-button full" id="continue-shopping" style="margin-top:17px">Tiếp tục mua sắm</button></div>`}
function productDetail(id){const p=findProduct(id);if(!p)return;$('#product-detail').innerHTML=`<div class="detail-grid"><div class="detail-image"><img src="${p.image}" alt="${escapeHTML(p.name)}"></div><div class="detail-copy"><span class="eyebrow">${escapeHTML(p.brand)} / ${categories[p.category]}</span><h2 id="product-title">${escapeHTML(p.name)}</h2><div class="price">${money(p.price)}</div><p class="muted">${escapeHTML(p.description)}</p><dl class="detail-facts"><div><dt>Quy cách</dt><dd>${escapeHTML(p.size)}</dd></div><div><dt>Tồn kho minh họa</dt><dd>${p.stock} sản phẩm</dd></div><div><dt>Hạn sử dụng${p.sellerProvided?' (cửa hàng)':''}</dt><dd>${escapeHTML(p.expiry||'Chưa cập nhật')}</dd></div></dl><button class="button primary full" data-add="${p.id}" ${p.stock===0?'disabled':''}>${p.stock===0?'Hết hàng (mẫu)':'Thêm vào giỏ hàng + '}</button><p class="small muted" style="margin-top:16px">${p.sellerProvided?'Giá bán lẻ theo thông tin cửa hàng. Ảnh tham khảo; tồn kho hiển thị chỉ dùng cho bản thử nghiệm.':'Sản phẩm và giá minh họa.'} Thành phần và hướng dẫn trên nhãn cần đối chiếu hàng thực tế trước khi mở bán.</p></div></div>`;openDialog('#product-dialog')}
function startCheckout(){if(!state.cart.size){toast('Hãy thêm sản phẩm vào giỏ trước.');return}closeDialog('#cart-dialog');$('#checkout-summary').innerHTML='<h3>Đơn hàng của bạn</h3>'+cartItems().map(p=>`<div class="summary-item"><img src="${escapeHTML(p.image)}" alt=""><div>${escapeHTML(p.name)}<small>${escapeHTML(p.size)} × ${p.qty}</small></div><strong>${money(p.price*p.qty)}</strong></div>`).join('')+summaryHTML();if(state.session?.role==='customer'){const form=$('#checkout-form');if(!form.elements.name.value)form.elements.name.value=state.session.name;if(!form.elements.email.value)form.elements.email.value=state.session.email}openDialog('#checkout-dialog')}
function placeDemoOrder(event){event.preventDefault();const form=event.target;if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));for(const key of ['name','phone','province','ward','address'])if(!data[key]?.trim()){form.elements[key].focus();toast('Vui lòng điền đầy đủ thông tin giao hàng.');return}if(!state.cart.size)return;const items=cartItems();if(items.some(p=>p.qty>p.stock)){toast('Tồn kho đã thay đổi. Vui lòng kiểm tra lại giỏ hàng.');return}if(!['qr','card'].includes(data.payment))return;const order={id:'DEMO-'+String(state.orders.length+1).padStart(4,'0'),items:items.map(p=>({...p})),total:subtotal()+shippingFee,payment:data.payment,status:'Mới tạo',tracking:'',customer:{name:data.name.trim(),phone:data.phone,province:data.province.trim(),ward:data.ward.trim(),address:data.address.trim(),note:data.note.trim()}};state.orders.unshift(order);items.forEach(p=>findProduct(p.id).stock-=p.qty);state.cart.clear();renderCatalog();renderCart();form.reset();updatePaymentExplanation();closeDialog('#checkout-dialog');$('#order-result').innerHTML=`<div class="result-symbol" aria-hidden="true">✓</div><span class="eyebrow" style="margin-top:22px">HOÀN TẤT TRẢI NGHIỆM</span><h2 id="result-title">Đã tạo đơn thử nghiệm</h2><p class="muted">Không có tiền được thu hoặc hàng được gửi. Bạn có thể xem đơn này trong mục Quản lý thử nghiệm.</p><div class="result-reference"><small>MÃ ĐƠN THỬ NGHIỆM</small>${order.id}<div class="sum-row"><span>Tổng minh họa</span><strong>${money(order.total)}</strong></div><div class="small muted">${order.payment==='qr'?'Phương thức: QR ngân hàng':'Phương thức: thẻ ngân hàng'}</div></div><p class="notice">${order.payment==='qr'?'Khi kết nối tài khoản bán hàng, bước này sẽ hiển thị QR đúng số tiền và mã đơn. Hiện không có mã để quét.':'Khi kết nối cổng thanh toán, bạn sẽ được chuyển tới trang nhập thẻ của nhà cung cấp. Bản thử nghiệm không thu thập số thẻ.'}</p><button class="button primary full" id="finish-order">Tiếp tục khám phá ↗</button><p class="small muted" style="margin-top:16px">Đơn thử và tồn kho sẽ đặt lại khi tải lại trang.</p>`;openDialog('#result-dialog')}
function updatePaymentExplanation(){$('#payment-explainer').textContent=$('input[name=payment]:checked').value==='qr'?'Khi mở bán, mã QR sẽ gắn với số tiền và mã đơn của bạn. Bản thử nghiệm không tạo mã thanh toán.':'Khi mở bán, thông tin thẻ sẽ được nhập trên trang của cổng thanh toán. Bản thử nghiệm không yêu cầu số thẻ.'}
const info={about:['Về banhkeongoai','Một cửa hàng nhỏ dành cho những món yêu thích từ nhiều nơi: bánh kẹo, chocolate, chăm sóc da và thực phẩm bổ sung.','Đây là phiên bản trải nghiệm trước khi mở bán. Danh mục gồm sản phẩm do cửa hàng cung cấp và các sản phẩm mẫu. Ảnh tham khảo, tồn kho và thanh toán vẫn trong chế độ thử nghiệm.'],shipping:['Giao hàng & đổi trả','Cửa hàng dự kiến giao hàng toàn quốc qua đơn vị vận chuyển nội địa. Phí 30.000 ₫ trong bản trải nghiệm chỉ là số minh họa.','Hãng vận chuyển, thời gian giao hàng, cách đóng gói sản phẩm nhạy nhiệt và điều kiện đổi trả sẽ được xác nhận trước khi nhận đơn thật.'],privacy:['Thông tin cá nhân','Bản trải nghiệm không gửi thông tin đặt hàng tới máy chủ, không thu thập số thẻ và không lưu đơn sau khi tải lại trang. Vui lòng chỉ dùng thông tin giả.','Tài khoản thử nghiệm và thay đổi sản phẩm được lưu trong trình duyệt trên thiết bị của bạn; chúng không đồng bộ với thiết bị khác. Mật khẩu được dẫn xuất thành mã kiểm tra cục bộ, nhưng đây không thay thế bảo mật máy chủ.'],contact:['Liên hệ cửa hàng','Cửa hàng hiện bán hàng qua Facebook. Đường dẫn trang Facebook, số điện thoại và thông tin liên hệ chính thức sẽ được bổ sung trước khi mở bán.','Hiện chưa có kênh liên hệ được kết nối trong bản trải nghiệm.']};
function showInfo(type){const entry=info[type];if(!entry)return;$('#info-content').innerHTML=`<span class="eyebrow">BANHKEONGOAI</span><h2 id="info-title">${entry[0]}</h2>${entry.slice(1).map(t=>`<p>${t}</p>`).join('')}`;openDialog('#info-dialog')}
function renderAdmin(){if(state.session?.role!=='admin')return;$('#order-count').textContent=state.orders.length;$('#admin-products').innerHTML=PRODUCTS.map(p=>`<form class="admin-product-row" data-edit-product="${escapeHTML(p.id)}"><img src="${escapeHTML(p.image)}" alt=""><div><h3>${escapeHTML(p.name)}</h3><span class="small muted">${escapeHTML(p.brand)} · ${escapeHTML(p.size)}</span></div><label>Giá (VND)<input name="price" aria-label="Giá ${escapeHTML(p.name)}" type="number" min="1000" max="100000000" step="1000" required value="${p.price}"></label><label>Tồn kho<input name="stock" aria-label="Tồn kho ${escapeHTML(p.name)}" type="number" min="0" max="10000" step="1" required value="${p.stock}"></label><div class="admin-actions"><button class="button secondary" type="submit">Lưu nhanh</button><button class="text-button" type="button" data-edit-open="${escapeHTML(p.id)}">Sửa chi tiết</button></div></form>`).join('');renderOrders()}
function updateBrandOptions(){const current=state.brand;$('#brand').innerHTML='<option value="all">Tất cả thương hiệu</option>'+[...new Set(PRODUCTS.map(p=>p.brand))].sort((a,b)=>a.localeCompare(b,'vi')).map(b=>`<option value="${escapeHTML(b)}">${escapeHTML(b)}</option>`).join('');state.brand=[...$('#brand').options].some(o=>o.value===current)?current:'all';$('#brand').value=state.brand}
function slugify(value){const base=normalize(value).replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,60)||'san-pham';let id=base,n=2;while(findProduct(id))id=base+'-'+n++;return id}
function validImageURL(value){try{if(/^(?:\.\/)?assets\/[^?#]+/.test(value))return true;const url=new URL(value);return url.protocol==='https:'}catch{return false}}
function openProductEditor(id){if(state.session?.role!=='admin')return;const form=$('#product-editor-form'),p=id?findProduct(id):null;form.reset();form.elements.id.value=p?.id||'';$('#editor-title').textContent=p?'Sửa sản phẩm':'Thêm sản phẩm';if(p){for(const key of ['name','brand','category','size','price','stock','image','expiry','description'])form.elements[key].value=p[key]??'';form.elements.featured.checked=!!p.featured}else{form.elements.stock.value=10;form.elements.category.value='snacks'}openDialog('#product-editor-dialog')}
function showAuthTab(id){for(const tab of ['login','register','admin-login']){$('#'+tab+'-tab').setAttribute('aria-selected',String(id===tab));$('#'+tab+'-form').hidden=id!==tab}$('#account-title').textContent=id==='register'?'Đăng ký khách hàng':id==='admin-login'?'Chủ cửa hàng':'Đăng nhập';if(id==='admin-login'){const hasAdmin=accounts().some(a=>a.role==='admin');$('#admin-setup-fields').hidden=hasAdmin;$('#admin-confirm-label').hidden=hasAdmin;$('#admin-login-form').elements.name.required=!hasAdmin;$('#admin-login-form').elements.confirm.required=!hasAdmin;$('#admin-auth-submit').textContent=hasAdmin?'Đăng nhập quản trị':'Thiết lập quản trị trên thiết bị này';$('#admin-auth-help').textContent=hasAdmin?'Dùng tài khoản quản trị đã thiết lập trên trình duyệt này.':'Lần đầu: tạo một tài khoản chủ cửa hàng chỉ cho trình duyệt này.'}}
function renderOrders(){$('#admin-orders').innerHTML=state.orders.length?state.orders.map(o=>`<article class="admin-order"><header><strong>${o.id} · ${escapeHTML(o.customer.name)}</strong><strong>${money(o.total)}</strong></header><p>${o.items.map(p=>escapeHTML(p.name)+' × '+p.qty).join(' · ')}</p><p>${escapeHTML(o.customer.phone)} · ${escapeHTML([o.customer.address,o.customer.ward,o.customer.province].join(', '))}</p>${o.customer.note?`<p>Ghi chú: ${escapeHTML(o.customer.note)}</p>`:''}<p>Thanh toán mô phỏng: ${o.payment==='qr'?'QR ngân hàng':'Thẻ'} · Chưa thu tiền</p><label>Trạng thái thử nghiệm<select data-order-status="${o.id}">${['Mới tạo','Đang chuẩn bị','Đang giao','Hoàn tất','Đã hủy'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Mã vận đơn thử<input maxlength="60" placeholder="Nhập mã minh họa" data-order-tracking="${o.id}" value="${escapeHTML(o.tracking)}"></label></article>`).join(''):'<div class="empty-state"><h3>Chưa có đơn thử nghiệm</h3><p>Thử thêm sản phẩm vào giỏ và hoàn tất bước đặt hàng để thấy đơn tại đây.</p></div>'}
function adminTab(id){const isProducts=id==='products-tab';$('#products-tab').setAttribute('aria-selected',String(isProducts));$('#orders-tab').setAttribute('aria-selected',String(!isProducts));$('#products-tab').tabIndex=isProducts?0:-1;$('#orders-tab').tabIndex=isProducts?-1:0;$('#admin-products').hidden=!isProducts;$('#admin-orders').hidden=isProducts}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close')){b.closest('dialog').close();return}if(b.dataset.category){chooseCategory(b.dataset.category);return}if(b.dataset.detail){productDetail(b.dataset.detail);return}if(b.dataset.add){addToCart(b.dataset.add);return}if(b.dataset.qty){changeQty(b.dataset.qty,Number(b.dataset.delta));return}if(b.dataset.remove){state.cart.delete(b.dataset.remove);renderCart();return}if(b.dataset.info){showInfo(b.dataset.info);return}if(b.dataset.editOpen){openProductEditor(b.dataset.editOpen);return}switch(b.id){case'open-account':renderAccount();showAuthTab('login');openDialog('#account-dialog');break;case'login-tab':case'register-tab':case'admin-login-tab':showAuthTab(b.id.replace('-tab',''));break;case'logout':state.session=null;sessionStorage.removeItem(storageKeys.session);renderAccount();toast('Đã đăng xuất.');break;case'open-dashboard':closeDialog('#account-dialog');renderAdmin();openDialog('#admin-dialog');break;case'open-cart':renderCart();openDialog('#cart-dialog');break;case'continue-shopping':closeDialog('#cart-dialog');$('#catalog').scrollIntoView();break;case'start-checkout':startCheckout();break;case'clear-search':case'reset-filters':clearFilters();break;case'about-link':showInfo('about');break;case'finish-order':closeDialog('#result-dialog');$('#catalog').scrollIntoView();break;case'open-admin':if(state.session?.role==='admin'){renderAdmin();openDialog('#admin-dialog')}else{showAuthTab('admin-login');openDialog('#account-dialog');toast('Vui lòng đăng nhập bằng tài khoản chủ cửa hàng.')}break;case'add-product':openProductEditor();break;case'products-tab':case'orders-tab':adminTab(b.id);break}});
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}));
$('#search-form').addEventListener('submit',e=>{e.preventDefault();$('#catalog').scrollIntoView()});$('#search').addEventListener('input',e=>{state.query=e.target.value;renderCatalog()});$('#sort').addEventListener('change',e=>{state.sort=e.target.value;renderCatalog()});$('#brand').addEventListener('change',e=>{state.brand=e.target.value;renderCatalog()});$('#checkout-form').addEventListener('submit',placeDemoOrder);$$('input[name=payment]').forEach(r=>r.addEventListener('change',updatePaymentExplanation));
$('#admin-products').addEventListener('submit',e=>{e.preventDefault();if(state.session?.role!=='admin')return;const form=e.target;if(!form.reportValidity())return;const p=findProduct(form.dataset.editProduct);const price=Number(form.elements.price.value),stock=Number(form.elements.stock.value);if(!p||!Number.isSafeInteger(price)||price<1000||price>100000000||!Number.isSafeInteger(stock)||stock<0||stock>10000)return;p.price=price;p.stock=stock;if(state.cart.has(p.id)){if(stock===0)state.cart.delete(p.id);else if(state.cart.get(p.id)>stock)state.cart.set(p.id,stock)}persistProducts();renderCatalog();renderCart();toast('Đã lưu sản phẩm trên thiết bị này.');form.querySelector('[type=submit]').textContent='Đã lưu';setTimeout(()=>form.querySelector('[type=submit]').textContent='Lưu nhanh',1500)});
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target;if(!form.reportValidity())return;const account=await authenticate(form.elements.email.value,form.elements.password.value,'customer');if(!account){toast('Email hoặc mật khẩu khách hàng không đúng.');return}setSession(account);form.reset();toast('Đăng nhập thành công.')});
$('#register-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target;if(!form.reportValidity())return;if(form.elements.password.value!==form.elements.confirm.value){toast('Hai mật khẩu chưa khớp.');return}try{const account=await makeAccount(form.elements.name.value,form.elements.email.value,form.elements.password.value,'customer');setSession(account);form.reset();toast('Đã tạo tài khoản khách hàng trên thiết bị này.')}catch(error){toast(error.message)}});
$('#admin-login-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target;if(!form.reportValidity())return;const hasAdmin=accounts().some(a=>a.role==='admin');try{let account;if(hasAdmin){account=await authenticate(form.elements.email.value,form.elements.password.value,'admin');if(!account){toast('Email hoặc mật khẩu quản trị không đúng.');return}}else{if(form.elements.password.value!==form.elements.confirm.value){toast('Hai mật khẩu chưa khớp.');return}account=await makeAccount(form.elements.name.value,form.elements.email.value,form.elements.password.value,'admin')}setSession(account);form.reset();closeDialog('#account-dialog');renderAdmin();openDialog('#admin-dialog');toast(hasAdmin?'Đã đăng nhập quản trị.':'Đã thiết lập quản trị trên thiết bị này.')}catch(error){toast(error.message)}});
$('#product-editor-form').addEventListener('submit',e=>{e.preventDefault();if(state.session?.role!=='admin')return;const form=e.target;if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));const price=Number(data.price),stock=Number(data.stock);if(!Number.isSafeInteger(price)||price<1000||price>100000000||!Number.isSafeInteger(stock)||stock<0||stock>10000){toast('Giá hoặc tồn kho không hợp lệ.');return}const image=data.image.trim().replace(/^\/assets\//,'./assets/');if(!validImageURL(image)){toast('Ảnh phải là ./assets/... hoặc đường dẫn https://');form.elements.image.focus();return}const existing=data.id?findProduct(data.id):null;const product={...(existing||{}),id:existing?.id||slugify(data.name),name:data.name.trim(),brand:data.brand.trim(),category:data.category,size:data.size.trim(),price,stock,image,expiry:data.expiry.trim(),description:data.description.trim(),featured:form.elements.featured.checked,sellerProvided:existing?.sellerProvided||false};if(existing)Object.assign(existing,product);else PRODUCTS.unshift(product);persistProducts();updateBrandOptions();renderCatalog();renderCart();renderAdmin();closeDialog('#product-editor-dialog');toast(existing?'Đã cập nhật sản phẩm.':'Đã thêm sản phẩm trên thiết bị này.')});
$('#admin-orders').addEventListener('change',e=>{if(e.target.dataset.orderStatus){const o=state.orders.find(x=>x.id===e.target.dataset.orderStatus);if(o&&['Mới tạo','Đang chuẩn bị','Đang giao','Hoàn tất','Đã hủy'].includes(e.target.value)){const wasCancelled=o.status==='Đã hủy';const nextCancelled=e.target.value==='Đã hủy';if(wasCancelled&&!nextCancelled&&o.items.some(p=>findProduct(p.id).stock<p.qty)){e.target.value=o.status;toast('Không đủ tồn kho mẫu để khôi phục đơn.');return}if(nextCancelled&&!wasCancelled)o.items.forEach(p=>findProduct(p.id).stock+=p.qty);if(wasCancelled&&!nextCancelled)o.items.forEach(p=>findProduct(p.id).stock-=p.qty);o.status=e.target.value;renderCatalog();renderAdmin();toast('Đã đổi trạng thái đơn thử nghiệm.')}}if(e.target.dataset.orderTracking){const o=state.orders.find(x=>x.id===e.target.dataset.orderTracking);if(o){o.tracking=e.target.value.trim();toast('Đã lưu mã vận đơn thử nghiệm.')}}});
$('.admin-tabs').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'products-tab':e.key==='End'?'orders-tab':e.target.id==='products-tab'?'orders-tab':'products-tab';adminTab(next);$('#'+next).focus()}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!$('dialog[open]')&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus()}});
loadLocalProducts();state.session=readJSON(sessionStorage,storageKeys.session,null);if(state.session&&!accounts().some(a=>a.id===state.session.id&&a.role===state.session.role))state.session=null;
updateBrandOptions();renderAccount();
$('#hero-products').innerHTML=['haribo','ritter-sport','lindt'].map(id=>{const p=findProduct(id);return `<img src="${p.image}" alt="${escapeHTML(p.name)}" width="220" height="250" fetchpriority="high">`}).join('');renderCatalog();renderCart();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'search_sample_catalog',description:'Filter the visible demo catalog by search text. Returns matching sample products.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.query!=='string'||input.query.length>100||Object.keys(input).some(k=>k!=='query'))throw new Error('Invalid query');state.query=input.query;$('#search').value=input.query;renderCatalog();return{products:visibleProducts().map(p=>({id:p.id,name:p.name,price:p.price,stock:p.stock})),currency:'VND',demo:true}}},{name:'add_sample_to_cart',description:'Add a sample product to the visible demo cart. Does not place an order or charge money.',inputSchema:{type:'object',properties:{productId:{type:'string'},quantity:{type:'integer',minimum:1,maximum:100}},required:['productId','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.productId!=='string'||!Number.isInteger(input.quantity)||input.quantity<1||input.quantity>100||Object.keys(input).some(k=>!['productId','quantity'].includes(k)))throw new Error('Invalid cart input');if(!addToCart(input.productId,input.quantity))throw new Error('Insufficient sample stock');return{cart:cartItems().map(p=>({id:p.id,quantity:p.qty})),subtotal:subtotal(),currency:'VND',demo:true}}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}}
