const PRODUCTS = [
  {
    "id": "mivolis-calcium-d3",
    "brand": "Mivolis",
    "name": "Mivolis Calcium + D3",
    "size": "Lọ 300 viên",
    "category": "supplements",
    "price": 250000,
    "stock": 10,
    "sellerProvided": true,
    "expiry": "02/2029",
    "description": "Viên uống Calcium + D3. Giá bán lẻ 250.000 ₫/lọ 300 viên. Hạn sử dụng theo thông tin cửa hàng: 02/2029. Ảnh chỉ mang tính tham khảo; ngày in trên ảnh không đại diện cho lô hàng hiện tại.",
    "image": "./assets/mivolis-calcium-d3.png"
  },
  {
    "id": "doppelherz-magnesium-calcium-d3",
    "brand": "Doppelherz",
    "name": "Doppelherz aktiv Magnesium + Calcium + D3",
    "size": "Hộp 40 viên",
    "category": "supplements",
    "price": 185000,
    "stock": 10,
    "sellerProvided": true,
    "expiry": "01/2028",
    "description": "Viên uống Magnesium + Calcium + D3. Giá bán lẻ 185.000 ₫/hộp 40 viên. Hạn sử dụng theo thông tin cửa hàng: 01/2028. Ảnh chỉ mang tính tham khảo.",
    "image": "./assets/doppelherz-magnesium-calcium-d3.png"
  },
  {
    "id": "doppelherz-magnesium-400",
    "brand": "Doppelherz",
    "name": "Doppelherz aktiv Magnesium 400",
    "size": "Hộp 30 viên",
    "category": "supplements",
    "price": 160000,
    "stock": 10,
    "sellerProvided": true,
    "description": "Viên uống Magnesium 400. Giá bán lẻ 160.000 ₫/hộp 30 viên. Thành phần cụ thể và hạn sử dụng sẽ được cập nhật theo lô hàng thực tế. Ảnh chỉ mang tính tham khảo.",
    "image": "./assets/doppelherz-magnesium-400.png"
  },
  {
    "id": "haribo",
    "brand": "Haribo",
    "name": "Kẹo dẻo Goldbears",
    "size": "100 g",
    "category": "snacks",
    "price": 45000,
    "stock": 20,
    "description": "Kẹo dẻo hình gấu. Sản phẩm được chọn để minh họa danh mục bánh kẹo.",
    "image": "./assets/haribo.webp"
  },
  {
    "id": "ritter-sport",
    "brand": "Ritter Sport",
    "name": "Chocolate sữa Alpine Milk",
    "size": "100 g",
    "category": "chocolate",
    "price": 65000,
    "stock": 15,
    "description": "Thanh chocolate sữa Alpine Milk. Thông tin mẫu phục vụ trải nghiệm mua sắm.",
    "image": "./assets/ritter-sport.webp"
  },
  {
    "id": "lotus",
    "brand": "Lotus",
    "name": "Bánh quy Biscoff caramel",
    "size": "250 g",
    "category": "snacks",
    "price": 79000,
    "stock": 18,
    "description": "Bánh quy Biscoff vị caramel. Giá và tồn kho là dữ liệu minh họa.",
    "image": "./assets/lotus.webp"
  },
  {
    "id": "lindt",
    "brand": "Lindt",
    "name": "Chocolate Lindor sữa",
    "size": "200 g",
    "category": "chocolate",
    "price": 189000,
    "stock": 12,
    "description": "Hộp chocolate Lindor sữa. Sản phẩm mẫu để trải nghiệm chọn và đặt hàng.",
    "image": "./assets/lindt.webp"
  },
  {
    "id": "custas",
    "brand": "Orion",
    "name": "Bánh bông lan Custas kem sữa",
    "size": "6 bánh · 138 g",
    "category": "snacks",
    "price": 42000,
    "stock": 16,
    "description": "Bánh bông lan nhân kem sữa. Bao bì mẫu; xuất xứ nhập khẩu phải được xác nhận theo lô thực tế.",
    "image": "./assets/custas.webp"
  },
  {
    "id": "hello-panda",
    "brand": "Meiji",
    "name": "Bánh Hello Panda nhân chocolate",
    "size": "50 g",
    "category": "snacks",
    "price": 35000,
    "stock": 25,
    "description": "Bánh quy nhân chocolate Hello Panda. Sản phẩm minh họa cho danh mục bánh.",
    "image": "./assets/hello-panda.webp"
  },
  {
    "id": "hada-labo",
    "brand": "Hada Labo",
    "name": "Lotion Gokujyun",
    "size": "170 ml",
    "category": "skincare",
    "price": 225000,
    "stock": 10,
    "description": "Lotion Gokujyun. Phiên bản, thành phần và hướng dẫn dùng cần đối chiếu nhãn hàng thực tế.",
    "image": "./assets/hada-labo.webp"
  },
  {
    "id": "bioderma",
    "brand": "Bioderma",
    "name": "Nước tẩy trang Sensibio H2O",
    "size": "250 ml",
    "category": "skincare",
    "price": 269000,
    "stock": 8,
    "description": "Nước tẩy trang Sensibio H2O. Thông tin lô và nhãn sản phẩm sẽ được bổ sung trước khi mở bán.",
    "image": "./assets/bioderma.webp"
  },
  {
    "id": "blackmores",
    "brand": "Blackmores",
    "name": "Bio C 1000",
    "size": "150 viên",
    "category": "supplements",
    "price": 485000,
    "stock": 7,
    "description": "Sản phẩm bổ sung Bio C 1000. Đây là mục hàng mẫu, không phải hướng dẫn sử dụng hoặc khuyến nghị sức khỏe.",
    "image": "./assets/blackmores.webp"
  },
  {
    "id": "dhc",
    "brand": "DHC",
    "name": "Vitamin C",
    "size": "120 viên",
    "category": "supplements",
    "price": 135000,
    "stock": 15,
    "description": "Sản phẩm bổ sung Vitamin C. Thành phần, đối tượng và hướng dẫn dùng sẽ theo nhãn lô hàng thực tế.",
    "image": "./assets/dhc.webp"
  }
];
